### ISSUE TITLE
SpamWatch

### ISSUE THREAD

**Issue by ruizlenato** [peaktogoo/HarukaAya#46]
ERROR: Could not find a version that satisfies the requirement spamwatch (from -r requirements.txt (line 24)) (from versions: none)
ERROR: No matching distribution found for spamwatch (from -r requirements.txt (line 24))

**Comment by zakaryan2004** [comment]
Haruka Aya runs on Python 3, so do the requirements, so use Python 3 instead of Python 2 to install the requirements and run the bot. In any case, this isn't a Haruka Aya issue.
